name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - changeset-release/main

  
jobs:
  release:
    if: ${{ github.event.pull_request.merged == true }}
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 16.7
        uses: actions/setup-node@v2
        with:
          node-version: 16.7

      - name: Install Dependencies
        run: npm ci --prefer-offline

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run build && npx changeset publish --tag beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}